### ISSUE TITLE
Cube demo does not allocate depth buffer in device local heap

### ISSUE THREAD

**Issue by danginsburg** [LunarG/VulkanSamples#116]
I forked this repo to make an OpenVR version of the cube demo and discovered a bug that was causing perf issues with the cube demo.  In cube.cpp the call to  choose the heap in prepare_depth() is as follows:

        auto const pass =
            memory_type_from_properties(mem_reqs.memoryTypeBits, vk::MemoryPropertyFlagBits(0), &depth.mem_alloc.memoryTypeIndex);

It should ask for the device local heap:

        auto const pass =
            memory_type_from_properties(mem_reqs.memoryTypeBits, vk::MemoryPropertyFlagBits::eDeviceLocal, &depth.mem_alloc.memoryTypeIndex);

cube.c has the same issue.  When I went up to 8x MSAA in VR this was causing the depth clear to take 20+ms.

**Comment by mark-lunarg** [comment]
@jeremy-lunarg, @danginsburg, this'll have to be fixed in Vulkan-LoaderAndValidationLayers, but we can use this issue for tracking.

**Comment by jeremy-lunarg** [comment]
I've pushed a patch to Vulkan-LoaderAndValidationLayers, which should be merged soon. Thanks Dan.
