### ISSUE TITLE
Error: SPIRV_TOOLS_LIB-NOTFOUND.obj

### ISSUE THREAD

**Issue by computersarecool** [LunarG/VulkanSamples#121]
Hi,
I am trying to build these samples, that come with the `1.0.42.2` Vulkan SDK and I can't build them.  I have Windows 10 and am trying to build from Visual Studio.

I have successfully built `glslang` and, when building `spirv-tools`, I get:

`========== Rebuild All: 10 succeeded, 0 failed, 5 skipped ==========`

However, when trying to build the samples in Visual Studio I get:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'SPIRV_TOOLS_LIB-NOTFOUND.obj'	occlusion_query	C:\VulkanSDK\1.0.42.2\Samples\build\API-Samples\LINK	1	`

In many of the samples projects (only 5 build, and that error is the only one repeated for all the other files).

Do you have any suggestions for me to build these? Thanks

**Comment by karl-lunarg** [comment]
Did you run the `build_windows_samples.bat` file in the SDK Samples directory?

I did a fresh install of the SDK, opened the SDK Samples folder in Windows Explorer and double-clicked the `build_windows_samples.bat` file and everything built correctly.  Some of the resulting binaries can be found in `C:\VulkanSDK\1.0.42.2\Samples\build\API-Samples\Release`, for example.

I also opened the VULKAN_SAMPLES.sln solution found in the Samples\build folder with Visual Studio 2015 and was able to rebuild the entire solution.

There are three VS solutions involved here and they tend to rely on finding binaries in each others' `build` folders.  This might be the problem for you if you built glslang and spirv-tools "by hand" and didn't put the binaries in the places where the samples solution is expecting to find them.

**Comment by computersarecool** [comment]
That was it! On older versions of the SDK I built them all by hand they worked but this was easier and better! Thanks a ton @karl-lunarg

**Comment by cippyboy** [comment]
First error was that CMake was not in my PATH which required a reinstall ( initially I tried using Cmake to build the samples which obviously doesn't work now). Now I have MSBuild was not found. Please use a visual studio developer console, or put MSBuild.exe in your PATH.

Can the samples be any harder to build ?

**Comment by Flamaros** [comment]
It is also very long to build and takes a lot of space on hard drive.
