### ISSUE TITLE
sync object reuse when FRAME_LAG < number of swapchain images

### ISSUE THREAD

**Issue by cdotstout** [LunarG/VulkanSamples#131]
The cube demo defaults to three swapchain images, but FRAME_LAG is only 2.

Isn't this problematic because:

- initially, all 3 swapchain images may be available
- semaphores are provided to acquire then passed as wait semaphores to queuesubmit
- the third call to acquire reuses the first semaphore, but this may interfere with the use of that semaphore by the first batch

Please let me know if I'm misunderstanding the spec - thanks!

**Comment by cdotstout** [comment]
Found relevant language in section 6.4.4 of spec 1.0.48:
"Passing a semaphore to vkAcquireNextImageKHR is equivalent to temporarily importing semaphore state to that semaphore."
I think this addresses the issue I was describing regarding semaphores.
However, the fence passed to acquire needs the same treatment doesn't it?

**Comment by Tony-LunarG** [comment]
I haven't addressed this because of https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1677 which could change the way we throttle in cube.  I think the fences are ok because we always wait for the fence before we pass it to vkAcquireNextImage, but I see your point about re-using the semaphores.  Let's see how the above pull request goes before proceeding on this.  Thanks.

**Comment by Tony-LunarG** [comment]
I believe that with the PR mentioned above, that synchronization is correct.  The code uses image_acquired_semaphore[0] in AcquireNextImageKHR, then waits for that semaphore to be signalled in QueueSubmit, passing fences[0], and then waiting for fences[0] before re-using image_acquired_semaphore[0] again.  It must have signalled or we wouldn't have returned from WaitForFences.  @cdotstout would you agree?

**Comment by cdotstout** [comment]
Yes.  I think that the use of a fence in the swapchain acquire is problematic w.r.t to the spec (I think it needs the same treatment -- temporary importation of state -- as the semaphore); however, the cube no longer uses the acquire fence, so this issue isn't relevant to the cube.
