### ISSUE TITLE
Vulkan LunarG samples exits without any passing status/info on Linux

### ISSUE THREAD

**Issue by manishashirke** [LunarG/VulkanSamples#132]
Bellow samples on linux exits without any pass/fail info, also no rendering on screen.
01-init_instance
02-enumerate_devices
03-init_device
04-init_command_buffer
05-init_swapchain
06-init_depth_buffer
07-init_uniform_buffer
08-init_pipeline_layout
09-init_descriptor_set
10-init_render_pass
11-init_shaders
12-init_frame_buffers
13-init_vertex_buffer
14-init_pipeline
create_debug_report_callback

While in case of android it shows pass/fail.

**Comment by karl-lunarg** [comment]
These samples are meant to introduce Vulkan API concepts without necessarily drawing anything.
They also are not designed to be test cases.  We have no plan to change these aspects of this code.

**Comment by manishashirke** [comment]
Hi Karl,
Thanks for the quick information.
