### ISSUE TITLE
instance_layer_extension_properties ,instance_layer_properties and enable_validation_with_callback  samples not able to use layers. 

### ISSUE THREAD

**Issue by manishashirke** [LunarG/VulkanSamples#133]
When ran these samples on linux, they are not able to  use respective layers.

Output : 
ubuntu@tegra-ubuntu:~/dbuild/API-Samples$ ./instance_layer_extension_properties 
Instance Layers:   Blank here 

Samples that are affected : 
instance_layer_extension_properties
instance_layer_properties
enable_validation_with_callback

**Comment by karl-lunarg** [comment]
Tony, please try to repo.   My first guess is that the layers are not being found because they are not in the default search areas or VK_LAYER_PATH is not being set.

**Comment by Tony-LunarG** [comment]
Karl is right, the VK_LAYER_PATH environment variable needs to be set to run those samples effectively.  I've updated the 3 samples in question to print a message suggesting setting VK_LAYER_PATH when no layers are found.

**Comment by manishashirke** [comment]
Hi Tony,
Thanks for the reply.
I copied all .so (libVkLayer_core_validation.so, libVkLayer_object_tracker.so, libVkLayer_parameter_validation.so, libVkLayer_swapchain.so, libVkLayer_threading.so, libVkLayer_unique_objects.so, libVkLayer_utils.so) from dbuild/layers  to dbuild/API_SAMPLE
and set VK_LAYER_PATH=$PWD
still those samples not able to use layers.

**Comment by manishashirke** [comment]
Hi Tony,
This worked. 
VK_LAYER_PATH=~/VulkanSamples-master/dbuild/layers/
Closing ticket.
Thank you.
