### ISSUE TITLE
Messages not being logged with debug callback function

### ISSUE THREAD

**Issue by RenatoUtsch** [LunarG/VulkanSamples#135]
Hi,

I was having some problems and wanted to know why some validation layer messages are not being logged with the debug report callback. Instead, these messages are being logged directly to stdout and the debug report callback is never called (I even commented the debug report callback setup code, and only enabled the validation layers, and the errors were still printed to stdout).

I went to great lengths to write all debug report messages to a log file instead of to stdout, and while many validation layer messages are being logged correctly (at least the info messages are), some messages are just being written to stdout and NOT with the debug report callback. This breaks my system completely, as I do not see the validation layer errors in the log files.

Specifically, the error I see being written to stdout instead of logged with the debug report callback function is:
https://github.com/LunarG/VulkanSamples/blob/315b15c3d74eb1df11b992c2b9922cf98e939eb8/layers/swapchain.cpp#L194

Any ideas on how I might solve this and log everything with the debug report callback? The funny thing is that some messages are being logged (the info messages are), but not all of them.

**Comment by mark-lunarg** [comment]
Hello @RenatoUtsch, there are a couple of holes that messages can fall into, especially if you're trying to log messages before the instance is created (which does not appear to be the case here).  There's no difference between the way INFO and ERROR messages are handled other than the DebugReportFlag setting itself.  If you are willing and able to attach/paste in the source for your callback that'll make things go more smoothly.  Thanks!

**Comment by RenatoUtsch** [comment]
Yeah, the weird thing is that this is happening when cleaning up.

I'll write a simpler example where this still happens, will be back in a few days.

**Comment by RenatoUtsch** [comment]
Actually, this might make sense. VkDestroyInstance() is called after the debug report callback is cleaned up, so the validation layer has no option but to write to stdin.

Sorry, dumb question on my part, of course this would not be reported through the debug report callback as it was already deleted.
