### ISSUE TITLE
Android Samples with latest ndk update fails due to deprecated app_dummy() call

### ISSUE THREAD

**Issue by intelzombi** [LunarG/VulkanSamples#139]
after updating the ndk to: 15.0.4075724

there is a failure:
FAILED: .../Projects/VulkanSamples/API-Samples/utils/util.cpp
.../Projects/VulkanSamples/API-Samples/utils/util.cpp:861:5: error: 'app_dummy' is deprecated: Calls to app_dummy are no longer necessary. See https://github.com/android-ndk/ndk/issues/381. [-Werror,-Wdeprecated-declarations]
    app_dummy();
    ^
.../Android/Sdk/ndk-bundle/sources/android/native_app_glue/android_native_app_glue.h:340:5: note: 'app_dummy' has been explicitly marked deprecated here
    deprecated("Calls to app_dummy are no longer necessary. See "

The workaround is to comment out the app_dummy() call in util.cpp only creates another issue with ANativeActivity_onCreate  not being found when you run the application.  Not sure if this is an NDK issue or if there is a change needed to the build to accommodate the deprecation

**Comment by intelzombi** [comment]
Found a solution if you are interested.

comment out //app_dummy()

add the line
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -u ANativeActivity_onCreate")

int the API_Samples/Android/CMakeLists.txt file down by thee #build application's shared lib.

target_include_directories(vulkan_sample PRIVATE
                           ${CMAKE_SOURCE_DIR}/../data
                           ${GLMINC_PREFIX}
                           ${SHADERC_SRC}/third_party/spirv-tools/include
                           ${SHADERC_SRC}/third_party/spirv-tools/include/spirv-tools
                           ${CMAKE_SOURCE_DIR}/../android/vulkan_wrapper)

   set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -u ANativeActivity_onCreate")
  
target_link_libraries(vulkan_sample
                      log
                      ${UTILS_NAME}
                      shaderc_lib)

**Comment by ggfan** [comment]
yeah, info is in:
  https://github.com/android-ndk/ndk/issues/381

just do not remove app_dummy() yet: the deprecation is more or less or ndk-build; for cmake / gradle experimental build,  must manually add linker flags to make it still work.  Will update it since I just updated NDK's samples.

**Comment by intelzombi** [comment]
interesting.  looks like they've been fighting this one a while then.
Thanks

**Comment by ggfan** [comment]
Not really, just started last night to update ndk samples.  But I personally is not big fan of this change: I would not run to get code changed that fast:
  1) a function name into the build script
  2) if in the future clang linker changes, this will need to be changed again
  3) have a source code to call an init function to initialize a module is not that terrible, just this time it was named to be app_dummy() ( it would be great if it was named to be app_init())

tangling source code with build script should be avoided.

**Comment by ggfan** [comment]
anyhow, does not seem I could win the conversation with NDK team. app will have to do itself. Application's CMakeLists.txt need to handle it.  inserted a PR,  https://github.com/LunarG/VulkanSamples/pull/140 as @intelzombi stated.

thanks

**Comment by ggfan** [comment]
this should be fixed with code merged, please kindly check out and help close the issue. thanks

**Comment by intelzombi** [comment]
looks fixed to me
