### ISSUE TITLE
Detected Visual Studio Version as 00 0000

### ISSUE THREAD

**Issue by bblay** [LunarG/VulkanSamples#143]
Running `update_external_sources.bat --all` prints `Detected Visual Studio Version as 00 0000` and fails.
Perhaps it needs to be updated for _Visual Studio Community 2017_?

**Comment by bblay** [comment]
This happened because MSBuild.exe was not on the path.
#145 helped resolve this by finding it, using vswhere.

**Comment by Tony-LunarG** [comment]
The VulkanSamples repo is really a downstream repo from Vulkan-LoaderAndValidationLayers repo here:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers

update_external_sources.bat is owned by the above repo, so any issues or enhancements need to be made in that repo.  Thanks.
