### ISSUE TITLE
Vulkan smoke test stop rendering on display during long run (~15 hours)

### ISSUE THREAD

**Issue by manishashirke** [LunarG/VulkanSamples#150]
Vulkan smoke test stop rendering on display when keep it overnight for running.

**Comment by Tony-LunarG** [comment]
I started smoke and initially there are a lot of objects flying around the view frustum, but as the test ran, more and more of the objects either drifted off to the sides of the frustum, or off into the distance, becoming very hard to see.  By the end of 3 hours, only a few of the objects remained visible and I can imagines that after 15 hours, none of the objects would be visible.  I don't think the test stops rendering, I think it is just that none of the objects are visible anymore.

**Comment by courtney-g** [comment]
QED: Proof of heat death of the universe :-)

**Comment by karl-lunarg** [comment]
Beware the day of maximum entropy.

**Comment by chrisforbes** [comment]
Well, do we want to adjust this test so that the object density /doesn't/ fall off over time? Is that useful to someone as a stress test?

**Comment by courtney-g** [comment]
It might be nice, but I don't think it's necessary.
More of an extra credit assignment.

**Comment by karl-lunarg** [comment]
I can actually see a noticeable difference in density after just a few minutes, so this is probably worth fixing.  I think I have a one-line fix that I'll make an MR for in the upstream LVL repo.  Details will in that MR.  I'll leave this open until I apply the same fix to Hologram.

**Comment by karl-lunarg** [comment]
Fix also applied to Hologram via https://github.com/LunarG/VulkanSamples/commit/1adb2a92d667120d5989290032025c2727b92bd1.

**Comment by manishashirke** [comment]
Thanks for the fix.
