### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by bigdimboom** [LunarG/VulkanSamples#165]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
VULKAN_LOADER
    linked by target "01-init_instance" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "copy_blit_image" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "02-enumerate_devices" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "08-init_pipeline_layout" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "05-init_swapchain" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "vulkan_1_1_flexible" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "immutable_sampler" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "03-init_device" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "04-init_command_buffer" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "06-init_depth_buffer" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "07-init_uniform_buffer" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "create_debug_report_callback" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "09-init_descriptor_set" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "10-init_render_pass" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "multithreaded_command_buffers" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "12-init_frame_buffers" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "11-init_shaders" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "14-init_pipeline" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "13-init_vertex_buffer" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "15-draw_cube" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "16-vulkan_1_1" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "enumerate_devices_adv" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "init_texture" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "draw_textured_cube" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "dynamic_uniform" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "texel_buffer" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "events" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "instance_layer_properties" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "instance_extension_properties" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "instance_layer_extension_properties" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "enable_validation_with_callback" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "multiple_sets" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "template" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "separate_image_sampler" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "input_attachment" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "occlusion_query" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "pipeline_cache" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "pipeline_derivative" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "push_descriptors" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "push_constants" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "draw_subpasses" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "secondary_command_buffer" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "spirv_assembly" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "spirv_specialization" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "memory_barriers" in directory C:/VKExamples/VulkanSamples/API-Samples
    linked by target "validation_cache" in directory C:/VKExamples/VulkanSamples/API-Samples

Configuring incomplete, errors occurred!
See also "C:/VKExamples/VulkanSamples/build/CMakeFiles/CMakeOutput.log".
See also "C:/VKExamples/VulkanSamples/build/CMakeFiles/CMakeError.log".

**Comment by bigdimboom** [comment]
I've run "update_external_sources.bat" already. Where is this "Vulkan Loader" file?
![image](https://user-images.githubusercontent.com/6119906/37870600-08183458-2fa8-11e8-914d-268afdfbe74c.png)

**Comment by bigdimboom** [comment]
Found the solution: need to specify "Vulkan-1.lib" library

**Comment by Tony-LunarG** [comment]
If the build is working properly (and it is for me), you shouldn't have to specify "Vulkan-1.lib" anywhere.  Where / how did you specify it?  Could you post more of your build output?

**Comment by bigdimboom** [comment]
![image](https://user-images.githubusercontent.com/6119906/38174025-9ff87426-3594-11e8-8a30-6ae18d2e1204.png)

**Comment by Tony-LunarG** [comment]
Fixed in PR #166
