### ISSUE TITLE
VulkanSamples don't compile under linux, pthread error

### ISSUE THREAD

**Issue by KestutisMa** [LunarG/VulkanSamples#171]
Hello,
Trying to compile VulkanSamples as described in https://github.com/LunarG/VulkanSamples#linux-build
gives error: [CMakeError.log](https://github.com/LunarG/VulkanSamples/files/1977356/CMakeError.log)

**Comment by Tony-LunarG** [comment]
Are you seeing targets that aren't compiling or are you just referring to the errors in the CMakeError.log file?  The errors in the CMakeError.log are from CMake looking for packages on the system that are not absolutely necessary for compiling the samples.  If there are samples that aren't compiling for you, can you list them here?

**Comment by KestutisMa** [comment]
Thank you for reply, I found that issue is caused by "download as zip" instead using git, using 'git clone' solves problem. Also using 'git clone git@github.com:LunarG/VulkanSamples.git' as described https://github.com/LunarG/VulkanSamples#clone-the-repository gives access error, but 'git clone https://github.com/LunarG/VulkanSamples' works.
