### ISSUE TITLE
init_renderpass uses initialLayout = UNDEFINED when using loadOp=LOAD

### ISSUE THREAD

**Issue by ratchetfreak** [LunarG/VulkanSamples#197]
https://github.com/LunarG/VulkanSamples/blob/9cbde4db68a38f8e108560741a97d759f76a9eb3/API-Samples/utils/util_init.cpp#L1159-L1168

When `clear` is false `initialLayout` is still set to `UNDEFINED`. This is invalid.

**Comment by Tony-LunarG** [comment]
So instead of LOAD_OP_LOAD, it should be LOAD_OP_DONT_CARE?  That would make sense.  Is there a valid usage for this case that we can get into the validation layers?

**Comment by ratchetfreak** [comment]
or keep the load_op_load, but give a valid initial layout. 

Depends on what you actually expect when clear is false.

**Comment by Tony-LunarG** [comment]
Fixed in #280
