### ISSUE TITLE
apt not works for ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by adammaj1** [LunarG/VulkanSamples#209]
Hi, 

I have done : 
      `sudo apt update ` 
      `sudo apt install lunarg-vulkan-sdk`

result: no such package found : 

`Czytanie list pakietów... Gotowe`
`Budowanie drzewa zależności `      
`Odczyt informacji o stanie... Gotowe`
`E: Nie udało się odnaleźć pakietu lunarg-vulkan-sdk`

I will try to build it
Adam

**Comment by johnzupin** [comment]
Did you configure your repos? Follow these steps at [https://vulkan.lunarg.com/sdk/home](https://vulkan.lunarg.com/sdk/home):

![howtogettorepoconfig](https://user-images.githubusercontent.com/3836693/50698370-f6044f00-1001-11e9-8201-7217a3fab358.png)

**Comment by johnzupin** [comment]
I believe samples are not included in the Ubuntu SDK packages currently. You probably need to build this repo.

**Comment by Tony-LunarG** [comment]
Closing.  Please re-open if there is still a problem
