### ISSUE TITLE
build_windows_samples.bat and latest Cmake incompatibility.

### ISSUE THREAD

**Issue by genious7** [LunarG/VulkanSamples#251]
The latest  versions of cmake require the -A x64 flag instead of appending w64 to %version_string% if you are using the Visual Studio 16 2019 generator.

See [here](https://cmake.org/cmake/help/git-stage/generator/Visual%20Studio%2016%202019.html)

**Comment by mikew-lunarg** [comment]
Yes, with VS2019, it appears [CMake is explicitly moving away from the architecture suffix on the generator name](https://github.com/Kitware/CMake/commit/57e48f16f2c3b73fb27057267c8092a41005bb75#diff-0e6bce6e358ad6bca783c6d14623613cR8), to using the -A switch.  See also
- VS2019 generator was added at [CMake 3.14](https://cmake.org/cmake/help/v3.14/manual/cmake-generators.7.html#visual-studio-generators)
- The [CMAKE_GENERATOR_PLATFORM ](https://cmake.org/cmake/help/v3.10/variable/CMAKE_GENERATOR_PLATFORM.html) variable, which is set by the [-A commandline option](https://cmake.org/cmake/help/v3.10/manual/cmake.1.html#options), works for our supported VS versions.

**Comment by Tony-LunarG** [comment]
Fixed via #252
