### ISSUE TITLE
Is 160MB per built API sample expected?

### ISSUE THREAD

**Issue by yay** [LunarG/VulkanSamples#254]
I just checked out and built this project and its dependencies using the `update_deps.py` as per instructions in the `BUILD.md` and it worked without a hitch, which is awesome. All examples I've tried running run. There's only one thing I wonder about and it's the size of the built examples:

![Screenshot from 2019-07-28 14-39-56](https://user-images.githubusercontent.com/1799756/62007525-5f86af00-b146-11e9-9881-5e6f50a3cc92.png)

160MB per executable. Is this expected?

**Comment by Tony-LunarG** [comment]
Unfortunately it is expected.  Most of the size comes from linking in glslang to be able to compile glsl to spirv.  I'm not aware of any way to generate glslang shared libraries, so each sample statically links the glslang libraries.

**Comment by yay** [comment]
Thanks for your reply. That makes sense. I just wanted to confirm if it's something wrong with my configuration. I'll close this now.

**Comment by johnkslang** [comment]
Properly built glslang is only a few MB, not 160MB.

Perhaps you are also including many other tools, like optimizers, validators, etc.

**Comment by johnkslang** [comment]
>  compile glsl to spirv. 

That requires a few MB.

> I'm not aware of any way to generate glslang shared libraries, so each sample statically links the glslang libraries.

People have contributed work to make shared libraries for glslang. It's in the build scripts, though I have not tried it out myself.

**Comment by Tony-LunarG** [comment]
It appears that the original question was about a debug build. Building Release, the glslang libraries and resulting samples are only a few MB (3.5 on my Windows build) as John mentioned above.   Debug is the default build configuration, so I would guess that is what the original question was about.

**Comment by dneto0** [comment]
I took a quick look.

The SPIRV-Tools library pulled in for Glslan'gs HLSL legalization is libSPIRV-Tools-opt.

On disk, Linux x86-64 binaries for libSPIRVTools-opt.a is 556MB for debug (!!), and 2.26MB for release.

I haven't got numbers for shared libraries on hand.
