### ISSUE TITLE
VK_FORMAT_D24_UNORM_S8_UINT incorrectly assumed supported on Android

### ISSUE THREAD

**Issue by c0d1f1ed** [LunarG/VulkanSamples#259]
https://github.com/LunarG/VulkanSamples/blob/8f5a4a661d073128989dd7515a556d19042afb6d/API-Samples/utils/util_init.cpp#L600 assumes VK_FORMAT_D24_UNORM_S8_UINT is supported on Android. I'm not aware of any such guarantee.

Instead, the Vulkan 1.1 spec states that "VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT feature must be supported for at least one of VK_FORMAT_X8_D24_UNORM_PACK32 and VK_FORMAT_D32_SFLOAT, and must be supported for at least one of VK_FORMAT_D24_UNORM_S8_UINT and VK_FORMAT_D32_SFLOAT_S8_UINT."

Thus conformant implementations may support only VK_FORMAT_D32_SFLOAT_S8_UINT as a format with stencil aspect. One such case is SwiftShader, which fully passes both dEQP-VK and Android 10 CTS.

This bug is causing these sample applications to crash.

**Comment by Tony-LunarG** [comment]
Fixed via #262
