### ISSUE TITLE
gradle issues

### ISSUE THREAD

**Issue by tpalli** [LunarG/VulkanSamples#261]
I had to upgrade Android Studio, it is now 3.5.1. After this I haven't been able to build the samples. I tried first fixing and older repo I had and now pulled the latest but that one fails as well. The method I'm doing is 'import existing android project'. Gradle cannot parse following lines in build.gradle:

```
@OTHER_FLAGS@
@ASSET_DIR@
@VALIDATIONLAYER_PACKING@
```
When I remove this it starts to complain:

```
Plugin with id 'com.android.application' not found.
```
Which gradle version should I be using? The files are configured for 5.1.1 but it does not seem to work 'out of the box'?

**Comment by tpalli** [comment]
I also noticed gradle-wrapper.properties says '5.1.1' but then build.gradle refers to gradle '3.4.1' ?

**Comment by tpalli** [comment]
FWIW I got it working using some ancient hash and older gradle, Android Studio recommends a gradle update there but I just ignore it and it works. Would appreciate some better instructions how to setup current git HEAD working with latest Android Studio.

**Comment by cnorthrop** [comment]
Adding Gerry (@ggfan) who might be able to help out here.

**Comment by ggfan** [comment]
probably you are pointing to the different build.gradle file.  If you have used "import samples" way, then your project is set with the top-level build.gradle ( settings.gradle etc ):
  ${your-source-dir}/build.gradle.

( you probably points your Android studio to the API-Samples/android/project_template/build.gradle, which is used to generate other build.gradle files. it is confusing at least, I understood in the last 4 years )

**Comment by Tony-LunarG** [comment]
Assuming ggfan's answer is sufficient. Closing

**Comment by tpalli** [comment]
Sorry I've been busy with other stuff :/ I'll try to test this again soon and let know if I succeeded.
