### ISSUE TITLE
Missing include folder

### ISSUE THREAD

**Issue by gazzatav** [LunarG/VulkanSamples#275]
The [online tutorial](https://vulkan.lunarg.com/doc/sdk/1.1.130.0/linux/tutorial/html/00-intro.html) states that the header vulkan.h can be found in the include folder in the Samples repository.  Having just cloned the Samples repo and run `find . -name *.h` I'm pretty sure that vulkan.h is not present.  This is not much of a problem for me as I have installed the sdk and have vulkan.h,  vulkan.hpp, vulkan/vulkan.h and vulkan/vulkan.hpp in /usr/include.  I did waste some time looking though and I did read the README.md again to see if I'd missed something about it.  Is there a reason why it's not present?
Thanks

**Comment by Tony-LunarG** [comment]
Fixed via #276

**Comment by gazzatav** [comment]
Maybe some kind person could update the tutorial because it still says:

> It is also useful to be able to easily access the vulkan.h header file for reference as you look at the sample code. This file can be found in the Samples repository, under the include directory.

Thanks

**Comment by Tony-LunarG** [comment]
If you are referring to the online tutorial on Lunar Exchange, that will be updated when we release the next Vulkan SDK, planned to be before the end of January.

**Comment by gazzatav** [comment]
Yes, the tutorial in the link in my original post. Thanks.
