### ISSUE TITLE
[Can not find ]fatal error: '15-draw_cube.vert.h' file not found

### ISSUE THREAD

**Issue by a31515034** [LunarG/VulkanSamples#288]
I followed the process, tried many methods, and couldn't find the header file
Is there something wrong with me?

thx

**Comment by Tony-LunarG** [comment]
That file is generated as part of the build process.  On Windows and Linux, cmake should add a step to each sample's build to pass their .vert and .frag shaders to glslangValidator and put the resulting spirv in a struct in a .vert.h or .frag.h file to be included by the sample.  These are generated into <build>/API-Samples/ShaderHeaders.  On Android, there now a step to "python3 ./compile_shaders.py" in the API-Samples/android directory before the call to gradlew.
What platform are you building on?  Do you see any files in <build>/API-Samples/ShaderHeaders?

**Comment by a31515034** [comment]
I am using android studio on windows，
build / API-Samples / ShaderHeaders is empty and has no files ，
I followed the official instructions https://developer.android.com/ndk/guides/graphics/getting-started to do,
Or am I missing something?


thank you for your help.

**Comment by a31515034** [comment]
Supplementary explanation,
Android studio Gradle plugin Version 3.4.1
Gradle Version  5.1.1
NDK 21.0.6113669

**Comment by Tony-LunarG** [comment]
Where the instructions say:
cd android
./gradlew build

Instead do:
cd android
python3 ./compile_shaders.py
./gradlew build

I'll try to figure out how to update that documentation

**Comment by Tony-LunarG** [comment]
@ggfan would you be able to help add a step to the build process in https://developer.android.com/ndk/guides/graphics/getting-started ?

**Comment by ggfan** [comment]
got it.  let me take a look

**Comment by a31515034** [comment]
C:\VulkanSamples\API-Samples\android>python3.\compile_shaders.py.\gradlew build
Is that right?

But it shows,
System can not find the route.

Sorry

**Comment by Tony-LunarG** [comment]
Two commands executed in VulkanSamples\API-Samples\android
python3 .\compile_shaders.py
.\gradlew build

**Comment by ggfan** [comment]
this then need to be executed earlier before starting android studio, before
```
cd VulkanSamples/API-Samples
cmake -DANDROID=ON -DABI_NAME=abi
cd android.  <=== new
python3 .\compile_shaders.py <===new
``` 

So both command line and IDE could proceed, correct?

**Comment by a31515034** [comment]
python3 .\compile_shaders.py  
no response

Execute next
.\gradlew build
Run out of error
-----------------------------
* What went wrong:
Could not create an instance of type org.gradle.initialization.DefaultSettings_Decorated.
> Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Tony-LunarG** [comment]
@ggfan, that looks right to me. @a31515034 - I'm not sure what's going on there.

**Comment by a31515034** [comment]
> 然後需要在啟動android studio之前，
..........
> 這樣命令行和IDE都可以繼續，對嗎？

 cd VulkanSamples/API-Samples
cmake -DANDROID=ON -DABI_NAME=armeabi-v7a 

ok

python3 .\compile_shaders.py
no response

**Comment by ggfan** [comment]
almost: 
```
cd android
python3 compile_shaders.py

```

**Comment by a31515034** [comment]
> @ggfan, that looks right to me. @a31515034 - I'm not sure what's going on there.

Thank you very much
I will try again
Hope for a good result

**Comment by a31515034** [comment]
I try
" python compile_shaders.py  "
Remove "3" to execute

result
------------------------------
OSError: [WinError 193] %1 不是有效的 Win32 應用程式。
Traceback (most recent call last):
  File "compile_shaders.py", line 30, in <module>
    subprocess.check_call(args)
  File "C:\Users\TERRY1~1\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\TERRY1~1\\AppData\\Local\\Programs\\Python\\Python36-32\\python.exe', '..\\..\\scripts\\generate_spirv.py', 'C:\\VulkanSamples\\API-Samples\\android\\..\\11-init_shaders\\11-init_shaders.frag', 'C:\\VulkanSamples\\API-Samples\\android\\ShaderHeaders\\11-init_shaders.frag.h', '..\\..\\glslang\\bin\\glslangValidator', 'false']' returned non-zero exit status 1.

sorry,
Do you know why?

I have used python 32 bit

**Comment by ggfan** [comment]
while this one is simple:  you have to install python3.

**Comment by a31515034** [comment]
I installed Python 3.6.0 -32bit

**Comment by ggfan** [comment]
@Tony-LunarG  it is fixed now on the documentation page:  https://developer.android.com/ndk/guides/graphics/getting-started
@a31515034 I do not know what is happening there.  Tony might be able to see whether it works on his end for windows. Linux seems to be ok. I will try later with a windows machine and let you know if you still have the issue.

**Comment by Tony-LunarG** [comment]
Thanks @ggfan.  I've never built samples for Android on anything but Linux.

**Comment by a31515034** [comment]
@ggfan 
sorry,
always trouble you,

Thank you very much

**Comment by a31515034** [comment]
> Thanks @ggfan. I've never built samples for Android on anything but Linux.

@Tony-LunarG 
It's ok
Thank you very much

**Comment by a31515034** [comment]
I found out today,
carried out,    " cmake -DANDROID=ON -DABI_NAME=armeabi-v7a "

The following message appears
----------------------------------------------------------------------------------
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- Building for: Visual Studio 14 2015
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.
-----------------------------------------------------------------------------
Is there any problem with this part?

**Comment by a31515034** [comment]
@ggfan sorry to bother you,
 I found out today,
> carried out, " cmake -DANDROID=ON -DABI_NAME=armeabi-v7a "
> 
> ## The following message appears
> CMake Warning:
> No source or binary directory provided. Both will be assumed to be the
> same as the current working directory, but note that this warning will
> become a fatal error in future CMake releases.
> 
> -- Building for: Visual Studio 14 2015
> CMake Warning (dev) in CMakeLists.txt:
> No project() command is present. The top-level CMakeLists.txt file must
> contain a literal, direct call to the project() command. Add a line of
> code such as
> 
> ```
> project(ProjectName)
> ```
> 
> near the top of the file, but after cmake_minimum_required().
> 
> ## CMake is pretending there is a "project(Project)" command on the first
> line.
> This warning is for project developers. Use -Wno-dev to suppress it.
> Is there any problem with this part?

**Comment by Tony-LunarG** [comment]
@a31515034  did you get your build working?  If not, can you post all of the output of cmake -DANDROID=ON -DABI_NAME=armeabi-v7a?

**Comment by sj6219** [comment]
if I executed  "cmake -DANDROID=ON -DABI_NAME=arm64-v8a",
then, error message is  
============================
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
CMake Error in CMakeLists.txt:
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified
============================
.

So, when I executed
"cmake -G "Visual Studio 16 2019" -DANDROID=ON -DABI_NAME=arm64-v8a"
, '15-draw_cube.vert.h' file was not created.

What can I do ?

**Comment by a31515034** [comment]
> @ a31515034 您的構建成功了嗎？如果沒有，您可以發布cmake -DANDROID = ON -DABI_NAME = armeabi-v7a的所有輸出嗎？

@Tony-LunarG 
I have successfully built,
Thank you for your previous help,

**Comment by sj6219** [comment]
I built with [Windows Build](https://github.com/LunarG/VulkanSamples/blob/master/BUILD.md#building-on-windows).
So. I got  `15-draw_cube.vert.h` file.

**Comment by ggfan** [comment]
@Tony-LunarG android/compile_shaders.py does not seem to be ready for windows:
https://github.com/LunarG/VulkanSamples/blob/master/API-Samples/android/compile_shaders.py#L9
the validator and assembler would install Linux only, it probably will not work for windows.  may you check that out?

**Comment by ggfan** [comment]
@a31515034:  you could manually download the 2 tools:
- [glslang](https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-windows-x64-Release.zip), unzip it into your $VulkanSamples\glslang (glslang\bin\Validator.exe needs to be there )
- [spirv-tools ](https://github.com/KhronosGroup/SPIRV-Tools/releases/download/master-tot/SPIRV-Tools-master-windows-x64-Release.zip), unzip it into your $VulkanSamples\spriv-tools ( make sure spirv-tools\bin\spirv-as.exe is there): not very necessary , but maybe just install it in case you use assembly shaders

details are inside [compile_shaders.py](https://github.com/LunarG/VulkanSamples/blob/master/API-Samples/android/compile_shaders.py) file.

After that you could run the `python compile_shaders.py`. 

At this point, the projects are ready.  Make sure you set up the Android SDK and NDK Path correctly, one simple way: create a local.properties and insert:
- sdk.dir=c:\\your\\sdk\\dir
- ndk.dir=c:\\your\\sdk\\dir\\ndk  <=== depends on where you install it.  refer to [the do](https://github.com/android/ndk-samples/wiki/Configure-NDK-Path) for more info.

From here you could either use Android Studio or command line to build. I could run the cube sample on Pixel 3A with Android R Developer Preview 2.

You might see different things on your end, hopefully this helps.

As for the CMake warning, you could ignore it for now: should not prevent you from building it. We probably will fix it later together with other things ( if you want, just add a project("$the-sample-name") to CMakeLists.txt, that would silence it).

**Comment by Tony-LunarG** [comment]
FIxed with #289

**Comment by a31515034** [comment]
@ggfan Thank you very much

I originally directly modified "compile_shaders.py"
Modify the file name of the downloaded compressed file
Change to
"glslang-master-windows-x64-Release.zip"
"SPIRV-Tools-master-windows-x64-Release.zip"

**Comment by ggfan** [comment]
thank you @a31515034 ! probably next time you may create a Pull Request for it so we save our time of duplicating efforts.
