### ISSUE TITLE
Samples may try to use a queue family that the device was not created with.

### ISSUE THREAD

**Issue by mre4ce** [LunarG/VulkanSamples#31]
In init_device() a VkDevice is created with a single VkDeviceQueueCreateInfo for a queue family that supports VK_QUEUE_GRAPHICS_BIT. Note that this queue may not support presentation.

Later, in init_swapchain_extension() a VkSurfaceKHR is created, and an attempt is made to select a queue family that supports both VK_QUEUE_GRAPHICS_BIT and presentation on the VkSurfaceKHR. This may be a different queue family than the one the device was created with, in which case vkGetDeviceQueue with this queue family will fail.

In order to render to a window on Windows or Linux, Vulkan pretty much forces the following order of operation:

1. create platform window (HWND, xcb_window_t, etc.)
2. create VkSurfaceKHR for the window
3. create VkDevice with one or more queue families that support the required VK_QUEUE_?_BITs and presentation on the VkSurfaceKHR
4. create VkSwapchainKHR for the VkSurfaceKHR with imageSharingMode set to VK_SHARING_MODE_CONCURRENT in case there is a separate queue family for presentation

Also note that the init_swapchain_extension() code will select a separate queue family for presentation if there is no queue family that supports both VK_QUEUE_GRAPHICS_BIT and presentation. However, the code never uses the presentation queue family if it is different, and the code also does not error if there is no queue family that supports both VK_QUEUE_GRAPHICS_BIT and presentation.

Also note that init_texture() uses vkCmdCopyImage which requires a queue family that supports VK_QUEUE_TRANSFER_BIT.

**Comment by karl-lunarg** [comment]
Tony, please close if appropriate.

**Comment by Tony-LunarG** [comment]
Changes are in commit entitled "Ensure that queue family selected supports both graphics and present".
Please open another issue if this is not satisfactory.
