### ISSUE TITLE
VulkanSamples for MacOS

### ISSUE THREAD

**Issue by kondrak** [LunarG/VulkanSamples#317]
It would be great if the samples could be easily built and run on MacOS - especially when trying to provide a sample application for debugging purposes to either LunarG or Khronos. Are there any plans for it? If not, are there any major roadblocks preventing these samples from working on a MacOS?

**Comment by KarenGhavam-lunarG** [comment]
There are no plans to port the samples to macOS. In fact, we are going to remove the samples from the Vulkan SDK for Linux and Windows (we never offered them with the macOS SDK) in favor of promoting the KhronosGroup/Vulkan-Samples instead.

**Comment by jjYBdx4IL** [comment]
You should add that comment to the top level README.
