### ISSUE TITLE
GLSL shader "convention" for Vulkan.

### ISSUE THREAD

**Issue by mre4ce** [LunarG/VulkanSamples#33]
Some samples use the following vertex shader code:

        "   // GL->VK conventions\n"
        "   gl_Position.y = -gl_Position.y;\n"
        "   gl_Position.z = (gl_Position.z + gl_Position.w) / 2.0;\n"

This feels like a hack to me. Imho, the right thing to do would be to setup an appropriate projection matrix that converts to the correct clip space for Vulkan (Z=[0,1], +Y=down), as opposed to OpenGL (Z=[-1,1], +Y=up). GLSL is a shader language that isn't in any way tied to the OpenGL clip space. It is the projection matrix that specifies the conversion to clip space.

**Comment by Tony-LunarG** [comment]
I would agree that it is a hack, but it lets us use the incredibly useful glm library for matrix and transform operations.  Maybe there should be utility code to fix the glm matrix instead of hacking the shader.

**Comment by baldurk** [comment]
I believe the latest glm now has support for the Vulkan convention, so updating to a newer version should sort the problem nicely, probably?

**Comment by Tony-LunarG** [comment]
Good to hear - thanks!  I'll look into it.

**Comment by olvaffe** [comment]
This is how Hologram fixes the issue, commit 0dd36179880238014512c0637b0ba9f41febe803

**Comment by SaschaWillems** [comment]
Recent glm versions have [GLM_DEPTH_ZERO_TO_ONE](https://github.com/g-truc/glm/blob/78f686b4be6c623df829db58b974bf8d79461987/glm/gtc/matrix_transform.inl#L276) for adjusting depth clip space to Vulkan conventions. Though this doesn't influence the y-axis.

**Comment by Tony-LunarG** [comment]
I took Olv's suggestion and moved the transform out of the shaders and into the MVP matrix transforms. Changes committed to master.
