### ISSUE TITLE
Incorrect layer names for threading and unique_objects

### ISSUE THREAD

**Issue by courtney-g** [LunarG/VulkanSamples#43]
The names for the threading and unique_objects layers should be:
VK_LAYER_GOOGLE_threading
VK_LAYER_GOOGLE_unique_objects

Will post pull request with fix.

**Comment by Tony-LunarG** [comment]
Did you perchance get asked about a CLA when you issued the pull request?

Thanks,
Tony


On Thu, Feb 18, 2016 at 10:58 AM, Courtney Goeltzenleuchter <
notifications@github.com> wrote:

> The names for the threading and unique_objects layers should be:
> VK_LAYER_GOOGLE_threading
> VK_LAYER_GOOGLE_unique_objects
>
> Will post pull request with fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LunarG/VulkanSamples/issues/43>.
>



-- 
Tony Barbour
LunarG
tony@lunarg.com <karl@lunarg.com>

**Comment by courtney-g** [comment]
No, I didn't not see a CLA request. That may be because this isn't a
traditional Github pull request. I didn't make it from a forked repo, but
from a branch within the LunarG VulkanSamples repo.

Courtney

On Thu, Feb 18, 2016 at 11:50 AM, Tony-LunarG <notifications@github.com>
wrote:

> Did you perchance get asked about a CLA when you issued the pull request?
>
> Thanks,
> Tony
>
>
> On Thu, Feb 18, 2016 at 10:58 AM, Courtney Goeltzenleuchter <
> notifications@github.com> wrote:
>
> > The names for the threading and unique_objects layers should be:
> > VK_LAYER_GOOGLE_threading
> > VK_LAYER_GOOGLE_unique_objects
> >
> > Will post pull request with fix.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/LunarG/VulkanSamples/issues/43>.
> >
>
>
>
> --
> Tony Barbour
> LunarG
> tony@lunarg.com <karl@lunarg.com>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LunarG/VulkanSamples/issues/43#issuecomment-185856285>
> .
>



-- 
Courtney

**Comment by courtney-g** [comment]
See MR #44 for changes to fix this.

**Comment by courtney-g** [comment]
MR #44 has been committed to master.
