### ISSUE TITLE
init_depth_buffer tries to figure out which tiling method to use but it sets it to optimal regardless

### ISSUE THREAD

**Issue by CapsAdmin** [LunarG/VulkanSamples#50]
https://github.com/LunarG/VulkanSamples/blob/master/API-Samples/utils/util_init.cpp#L591-L603 
does nothing because of 
https://github.com/LunarG/VulkanSamples/blob/master/API-Samples/utils/util_init.cpp#L615

**Comment by Tony-LunarG** [comment]
Changes committed to master - thanks!
