### ISSUE TITLE
incorrect/incomplete order for "cube progression" in README.md

### ISSUE THREAD

**Issue by 3b** [LunarG/VulkanSamples#52]
README.md says
> Start with the instance sample, then device, initcommandbuffer, ...
> Each sample uses utility routines from the code from previous samples to get to the point to show something new. 

but `initcommandbuffer` does

```
    init_global_layer_properties(info);
    init_instance_extension_names(info);
    init_device_extension_names(info);
    init_instance(info, sample_title);
    init_enumerate_device(info);
    init_window_size(info, 500, 500);
    init_connection(info);
    init_window(info);
    init_swapchain_extension(info);
    init_device(info);
```

which looks like a bit more than `instance` and `device`. Some are in the list but after `commandbuffer`, while others aren't listed at all.

**Comment by Tony-LunarG** [comment]
Yes, and it could be clearer, but the progression is referring to the standalone samples, not utility calls.  There are no standalone samples for init_window_size, init_connection, init_window or init_swapchain_extension, although initswapchain covers all of those, but it needs a command buffer and so must come after initcommandbuffer.  A case could be made for the layer and extension samples, but we thought that they might distract from the strainght path to drawcube.  enumerate-adv certainly can be added and I'll fix the README to reflect that.

**Comment by Tony-LunarG** [comment]
I've updated the README and added enumerate
