### ISSUE TITLE
The API-Samples/utils.cpp::GLSLtoSPV contains memory leak.

### ISSUE THREAD

**Issue by Tomius** [LunarG/VulkanSamples#55]
The program and shader variables in the GLSLtoSPV function are not freed.

I think this code was copied from glslang/StandAlone/StandAlone.cpp::CompileAndLinkShaderUnits

That function ends with these few lines, but the cleanup logic wasn't copied into the GLSLtoSPV function.

    // Free everything up, program has to go before the shaders
    // because it might have merged stuff from the shaders, and
    // the stuff from the shaders has to have its destructors called
    // before the pools holding the memory in the shaders is freed.
    delete &program;
    while (shaders.size() > 0) {
        delete shaders.back();
        shaders.pop_back();
    }

**Comment by Tomius** [comment]
A possible fix would be:

bool GLSLtoSPV(const VkShaderStageFlagBits shader_type, const char *pshader,
               std::vector<unsigned int> &spirv) {
    EShLanguage stage = FindLanguage(shader_type);
    glslang::TShader shader(stage);
    glslang::TProgram program;
    const char *shaderStrings[1];
    TBuiltInResource Resources;
    init_resources(Resources);

    // Enable SPIR-V and Vulkan rules when parsing GLSL
    EShMessages messages = (EShMessages)(EShMsgSpvRules | EShMsgVulkanRules);

    shaderStrings[0] = pshader;
    shader->setStrings(shaderStrings, 1);

    if (!shader.parse(&Resources, 100, false, messages)) {
        puts(shader.getInfoLog());
        puts(shader.getInfoDebugLog());
        return false; // something didn't work
    }

    program.addShader(&shader);

    //
    // Program-level processing...
    //

    if (!program.link(messages)) {
        puts(shader.getInfoLog());
        puts(shader.getInfoDebugLog());
        return false;
    }

    glslang::GlslangToSpv(*program.getIntermediate(stage), spirv);

    return true;
}

Dynamic memory allocation is not necessary for this. 

Also a fflush(stdout); after the puts statements might be nice - if the program craches because someone forgets to check GLSLtoSPV's return code, the programmer won't see anything on the stdout.

**Comment by Tony-LunarG** [comment]
Thanks for the suggestion - committed to master
