### ISSUE TITLE
Vulkan sample test "copyblitimage" crashes on "N' based device

### ISSUE THREAD

**Issue by vrkotireddy** [LunarG/VulkanSamples#62]
assert(
(formatProps.linearTilingFeatures & VK_IMAGE_USAGE_TRANSFER_SRC_BIT) &&
"Format cannot be used as transfer source");

I don't see why this assert is needed and in fact what the app is doing is getting the physical device format properties using: vkGetPhysicalDeviceFormatProperties() and then checking/asserting if the format can be used as a transfer source (by checking for the bit: VK_IMAGE_USAGE_TRANSFER_SRC_BIT).
vkGetPhysicalDeviceFormatProperties() only returns one of the vkFormatProperties, so, the result should NOT be used to check if the image can be used as a source of a transfer command. I think the assert is wrong.

Removing the assert eliminates the crash and app runs fine.

Per spec: VK_IMAGE_USAGE_TRANSFER_SRC_BIT indicates that the image can be used as the source of a transfer command.

**Comment by courtney-g** [comment]
Looks like the sample is using the wrong enum, should be VK_FORMAT_FEATURE_BLIT_SRC_BIT as linearTilingFeatures is a VkFormatFeatureFlags not a VkImageUsageFlags.

**Comment by vrkotireddy** [comment]
Yeah, that should be it. either change the enum to VK_FORMAT_FEATURE_BLIT_SRC_BIT or just take that assert off. Either one will fix the crash.

**Comment by courtney-g** [comment]
On Wed, Apr 6, 2016 at 7:19 AM, vrkotireddy <notifications@github.com>
wrote:

> Yeah, that should be it. either change the enum to
> VK_FORMAT_FEATURE_BLIT_SRC_BIT or just take that assert off. Either one
> will fix the crash.
>
Yes, it should be  VK_FORMAT_FEATURE_BLIT_SRC_BIT. Looks like wrong enum
was used.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/LunarG/VulkanSamples/issues/62#issuecomment-206367250>
>



-- 
Courtney

**Comment by vrkotireddy** [comment]
Thanks. Closing the issue.
