### ISSUE TITLE
drawsubpasses sample crash: pipeline.pColorBlendState can NOT be set to VkPipelineColorBlendStateCreateInfo when there is only stencil attachment

### ISSUE THREAD

**Issue by vrkotireddy** [LunarG/VulkanSamples#63]
VkPipelineColorBlendStateCreateInfo (cb) – state setup with attachment count 1 (depth/stencil only attachment) and when creating the graphics pipeline object (VkGraphicsPipelineCreateInfo), color blend state was set to cb – which as per spec does **not **look right.

Spec: pColorBlendState is a pointer to an instance of the VkPipelineColorBlendStateCreateInfo structure, or** NULL** if the pipeline has rasterization disabled or **if the subpass of the render pass the pipeline is created against does not use any color attachments.**

So the code below needs to be changed:
VkGraphicsPipelineCreateInfo pipeline;
    pipeline.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pipeline.pNext = NULL;
    pipeline.layout = info.pipeline_layout;
    pipeline.basePipelineHandle = VK_NULL_HANDLE;
    pipeline.basePipelineIndex = 0;
    pipeline.flags = 0;
    pipeline.pVertexInputState = &vi;
    pipeline.pInputAssemblyState = &ia;
    pipeline.pRasterizationState = &rs;
    pipeline.pColorBlendState = &cb; This should be changed to  pipeline.pColorBlendState = NULL;
   .....
.......

and in the subpass2 (of renderpass 1), we can then set the state to &cb

/* this pipeline will run in the second subpass */
    pipeline.subpass = 1;
    pipeline.pColorBlendState = &cb; --> set here to &cb (as this will have color attachment).

This will fix the crash and renders the cubes (one left and one right in half full screen as expected)

**Comment by Tony-LunarG** [comment]
Fixed and committed to master.  Thanks!

**Comment by vrkotireddy** [comment]
Great, thanks Tony. I will close this out.
