### ISSUE TITLE
presentable image transition must happen only after acquire

### ISSUE THREAD

**Issue by ratchetfreak** [LunarG/VulkanSamples#75]
according to the [WSI swapchain spec](https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_wsi_swapchain) it's not allowed to do the transition before the first acquire of the image:

> The presentable images of a swapchain are owned by the presentation engine. An application can acquire use of a presentable image from the presentation engine. Use of a presentable image must occur only after the image is returned by vkAcquireNextImageKHR, and before it is presented by vkQueuePresentKHR. This includes transitioning the image layout and rendering commands.

This means that you need to keep a flag per image to see if it's been used already or always use VK_IMAGE_LAYOUT_UNDEFINED as the source.

**Comment by Tony-LunarG** [comment]
Changes to samples committed to master
