### ISSUE TITLE
cube.c transitions swapchain image layouts without acquiring the images first

### ISSUE THREAD

**Issue by 3b** [LunarG/VulkanSamples#76]
At https://github.com/LunarG/VulkanSamples/blob/master/demos/cube.c#L912 it sets the layout of the swapchain images to `VK_IMAGE_LAYOUT_PRESENT_SRC_KHR`, and as far as I can see it doesn't acquire the image first. 

 https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_wsi_swapchain says 

>  Use of a presentable image must occur only after the image is returned by vkAcquireNextImageKHR, and before it is presented by vkQueuePresentKHR. This includes transitioning the image layout and rendering commands.

**Comment by courtney-g** [comment]
It's okay to build command buffers if the application knows what image objects are used. Cannot submit the command buffers for processing without acquiring the image. Remember, we are not "using" the image until command buffers using the image have been submitted to a queue.

**Comment by ratchetfreak** [comment]
But you do transition all the images in the swapchain to PRESENT **before** ever acquiring them.

So either always transition from UNDEFINED or keep track of which ones have been transitioned to a known layout.

**Comment by courtney-g** [comment]
Agree, the current code might be okay if it only updated the layout on the active image but it changes the layout on both images when we know only one could be active at a time. Sounds like we should have a validation layer flagging this as an issue.

**Comment by Tony-LunarG** [comment]
Changes to cube and tri committed to LoaderAndValidationLayers master
