### ISSUE TITLE
Is it "legal" to call vkCmdBindDescriptorSets() when none of the previously bound pipeline's shader stages access any descriptor sets?

### ISSUE THREAD

**Issue by hiddenbitious** [LunarG/VulkanSamples#79]
I've been examining drawsubpasses.cpp. Before the last vkCmdDraw(), although none of the shaders in the previously bound pipeline access any desciptor sets, it does call vkCmdBindDescriptorSets(). Is there any purpose in calling it?

**Comment by Tony-LunarG** [comment]
My quick read through of the relevant sections of the spec lead me to say "yes, it's legal". When referring to shaders accessing resources bound through descriptor sets, the word "can" is regularly used, in a document that is not at all uneasy about using the word "must".  Do you see any language in the spec that implies it's illegal?

One reason I can see to call vkCmdBindDescriptorSets is that when the pipeline layout was created, it said that there was going to be one descriptor set, so the bind call is fulfilling that promise, even if the shader has no use for it.  I suppose one could create a different pipeline layout with no descriptor sets for the  second and third pipeline, but I'm at a loss to say if that's better or not.

**Comment by hiddenbitious** [comment]
"legal" wasn't the best word I could have chosen. In the spec it is stated that:
> A compatible descriptor set must be bound for all set numbers that any shaders in a pipeline access, at the time that a draw or dispatch command is recorded to execute using that pipeline. However, if none of the shaders in a pipeline statically use any bindings with a particular set number, then no descriptor set need be bound for that set number, even if the pipeline layout includes a non-trivial descriptor set layout for that set number.

So according to this, the call to vkCmdBindDescriptorSets() isn't illegal, but it is not needed. Likewise it wasn't called when the stencil_fullscreen_pipe, pipeline was bound (line 460).

So either way this is a minor issue

**Comment by Tony-LunarG** [comment]
I didn't realize that the call to vkCmdBindDescriptorSet was optional once the pipeline layout was specified with a descriptor set, but that's certainly what you quoted spec passage says.  I'll drop the unneeded calls.
