### ISSUE TITLE
memory flushing & invalidation inconsistency

### ISSUE THREAD

**Issue by Radamanthe** [LunarG/VulkanSamples#82]
According to the specification, a memory allocated without VK_MEMORY_PROPERTY_HOST_COHERENT_BIT set must be flushed/invalidated with vkFlushMappedMemoryRanges and vkInvalidateMappedMemoryRanges.

By studying all the samples, one can only conclude they don't respect the specs in that regard. No sample use vkInvalidateMappedMemoryRanges and only one (copyblitimage) uses vkFlushMappedMemoryRanges before unmapping memory. But many of them create memory objects without VK_MEMORY_PROPERTY_HOST_COHERENT_BIT set.

So what's the deal there? Do these samples simply assume that the memory type they obtained has this bit set? Looks quite dangerous to me.

**Comment by Radamanthe** [comment]
I may add that according to the specification and its list of possible bit combinations, there is only one possible bit combination with VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT set which can be non host coherent:

VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_CACHED_BIT

Hence that kind of memory could be a candidate for a request with only VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT set. Reading the spec, such memory would not be host coherent.

**Comment by Tony-LunarG** [comment]
You're correct that the allocation calls are wrong and I'm adding HOST_COHERENT to all of the requests.  I honestly don't think the HOST_COHERENT bit existed when we started writing these demos.

**Comment by Radamanthe** [comment]
Don't bother, I can do this work on all samples and do a pull request if you wish.

I just learned the "don't commit to master and pull request" rule the hard way ;) (must fix that first)
