### ISSUE TITLE
Overlay layer sample confusing data map usage.

### ISSUE THREAD

**Issue by mre4ce** [LunarG/VulkanSamples#84]
The Layer-Samples/Overlay/overlay.cpp probably works correctly but don't the following lines use different keys and therefore produce different objects?

```
layer_data *my_data = get_my_data_ptr(get_dispatch_key(*pInstance), layer_data_map);
layer_data *my_device_data = get_my_data_ptr(get_dispatch_key(*pDevice), layer_data_map);
```

**Comment by chrisforbes** [comment]
@mre4ce Yes, the instance key and the device key are different. A very small subset of `layer_data` is actually valid in the instance case.

This is what all the layers do, and you're right -- it's confusing what's valid on which object when. There has been some discussion of splitting `layer_data` into an instance type and a device type, which would make this a lot clearer, but it hasn't happened.

Hopefully that answers your question?

**Comment by mre4ce** [comment]
It does. Thanks!

I would vote for fixing this or at least initializing the layer_data.

**Comment by karl-lunarg** [comment]
This change is on a long-term list of things to do.   While it may be more clear to split the layer data, for now, it works fine as it is.  And the change would be very large with little actual gain.
