### ISSUE TITLE
Better description of how to build.

### ISSUE THREAD

**Issue by chisophugis** [LunarG/VulkanSamples#85]
I wanted to make a small patch against vulkaninfo.c but I was looking at the one from the latest sdk (1.0.13.0) from the lunarg website. So I decided to check out this repository and make the patch here. However, I was unable to build the code in this repository.
This is my CMake output.
[cmake_output.txt](https://github.com/LunarG/VulkanSamples/files/276665/cmake_output.txt)

I tried various things and wasted more time than I care to admit, but nothing seemed like it was the "intended" way to build the code in this repository. What is the usual workflow that people use for building? It would be nice to document that.
What other repos do I have to check out? Where do I have to check them out? What do I have to build before building this? Etc.

**Comment by Tony-LunarG** [comment]
You're right - the build documentation is out of date.  We've moved glslang and spirv-tools to be inside the repo instead of asking for them to be peers.  It looks like you need to run update_external_sources.sh before you run cmake, and I need to update the README.

**Comment by chisophugis** [comment]
Thanks! I used `update_external_sources.sh` and everything worked flawlessly! Having that in the README would be fantastic.

**Comment by chisophugis** [comment]
Just noticed that you added https://github.com/LunarG/VulkanSamples#clone-the-repository, thanks!
