### ISSUE TITLE
keyboard input not working

### ISSUE THREAD

**Issue by sdack** [LunarG/VulkanSamples#89]
I am running the examples and noticed that keyboard input doesn't work.

Moving the mouse to rotate the view and using the right mouse button to zoom in and out is working.
The graphics themselves display and appear to be running fine.

The system is Linux Debian stretch/sid with kernel 4.6.2 on an AMD FX 8350 with an Nvidia GTX 960.
Xfce 4.12.13, Xorg 1.18.3, libxcp 1.11.1, libXau 1.0.8, libXdmcp 1.1.2, libvulkan 1.0.8.0, libassimp 3.2

Also, thank you for the examples.

**Comment by Tony-LunarG** [comment]
Which sample in particular?  Most of our samples don't process keyboard input.

**Comment by sdack** [comment]
I may have been confusing your examples with somebody else's then. I cannot tell which ones I was looking at. The sources weren't clear about it and I had to take a guess. If your examples do not take keyboard input then they were likely not yours. Regards.
