### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by xyproto** [LunarG/VulkanSamples#90]
When building, I get the following error:

```
[67/204] Building CXX object layers/CMakeFiles...ayer_core_validation.dir/core_validation.cpp.o
FAILED: layers/CMakeFiles/VkLayer_core_validation.dir/core_validation.cpp.o 
/usr/bin/c++   -DDATADIR=\"share\" -DSYSCONFDIR=\"etc\" -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR -DVkLayer_core_validation_EXPORTS -I../include -I../layers -I../layers/../loader -I../layers/../include/vulkan -Ilayers -I../external/glslang -std=c++11 -Wpointer-arith -fPIC -MMD -MT layers/CMakeFiles/VkLayer_core_validation.dir/core_validation.cpp.o -MF layers/CMakeFiles/VkLayer_core_validation.dir/core_validation.cpp.o.d -o layers/CMakeFiles/VkLayer_core_validation.dir/core_validation.cpp.o -c ../layers/core_validation.cpp
../layers/core_validation.cpp: In function ‘VkResult core_validation::CreateShaderModule(VkDevice, const VkShaderModuleCreateInfo*, const VkAllocationCallbacks*, VkShaderModule_T**)’:
../layers/core_validation.cpp:8520:40: error: ‘SPV_ENV_VULKAN_1_0’ was not declared in this scope
     spv_context ctx = spvContextCreate(SPV_ENV_VULKAN_1_0);
                                        ^~~~~~~~~~~~~~~~~~
../layers/core_validation.cpp:8524:45: error: invalid conversion from ‘spv_diagnostic_t**’ to ‘uint32_t {aka unsigned int}’ [-fpermissive]
     auto result = spvValidate(ctx, &binary, &diag);
                                             ^~~~~
../layers/core_validation.cpp:8524:50: error: too few arguments to function ‘spv_result_t spvValidate(spv_const_context, spv_const_binary, uint32_t, spv_diagnostic_t**)’
     auto result = spvValidate(ctx, &binary, &diag);
                                                  ^
In file included from ../layers/core_validation.cpp:62:0:
/usr/include/spirv-tools/libspirv.h:393:14: note: declared here
 spv_result_t spvValidate(const spv_const_context context,
              ^~~~~~~~~~~
[72/204] Building CXX object tests/CMakeFiles/...der_validation_tests.dir/vktestframework.cpp.o
ninja: build stopped: subcommand failed.
```

This is on 64-bit Arch Linux with GCC 6.1.1, CMake 3.5.2 and Ninja 1.7.1.

**Comment by Tony-LunarG** [comment]
Sorry to take so long to get back to you.  Did you run the update_external_sources.sh script?

**Comment by xyproto** [comment]
Thanks for the help. I just tried with the latest commit and running the `update_external_source.sh` script first and it builds now.

Why is `update_external_source.sh` needed, though, instead of it being included in the CMake configuration and build process? I already have the spirv-tools (version 1.0.3), vulkan headers (version 1.0.17) and glslang (version 3.0.git1.e1cd410) installed on my system.

Should not the CMake configuration be able to detect and use these instead of refusing to build?

**Comment by karl-lunarg** [comment]
All three repos (https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers, https://github.com/LunarG/VulkanTools, and this one) are validated and tested against specific versions of spirv-tools and glslang.  So, adding these other dependencies to CMake wouldn't necessarily pick up versions that are known to work.

For example, there is a bug in the current version of glslang right now that keeps one of the samples from executing properly.  So, the update_external_sources script, in concert with a glslang revision file, obtains a working version.  There would be considerable risk in using whatever version a user has installed on their system.

**Comment by xyproto** [comment]
That's incorrect. CMake supports depending on specific versions of libraries. You could specify versions that are known to work. No need to vendor the libraries.

**Comment by karl-lunarg** [comment]
Sorry, I probably should have said "specific git commits" instead of "versions".

**Comment by xyproto** [comment]
I see. Thanks for the answers.
