### ISSUE TITLE
Linux build failure due to outdated broken glslang revision dependency.

### ISSUE THREAD

**Issue by HypnoGenX** [LunarG/VulkanSamples#93]
As first reported here; https://github.com/KhronosGroup/glslang/issues/344

The specific glslang revision pulled in by https://github.com/LunarG/VulkanSamples/blob/master/glslang_revision (4678ca9dacfec7a084dbc69bbe568bdad6889f1b at time of writing) fails to build on Linux. The issue is fixed in the current https://github.com/KhronosGroup/glslang HEAD, and probably earlier.

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers has the exact same issue, and this bug report is a duplication of my bug report there; https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/681

**Comment by karl-lunarg** [comment]
VulkanTools and VulkanSamples are downstream of LoaderAndValidationLayers, so once fixed in LVL, it will be fixed in VT and VS.  Closing since this is a duplicate.  Discussion should continue in the LVL bug:  KhronosGroup/Vulkan-LoaderAndValidationLayers#681
