### ISSUE TITLE
clears outside renderpasses are transfer operations

### ISSUE THREAD

**Issue by ratchetfreak** [LunarG/VulkanSamples#95]
https://github.com/LunarG/VulkanSamples/blob/master/API-Samples/membarriers/membarriers.cpp#L224

Here the access mask for the clear is set as COLOR_ATTACHMENT_WRITE however clears outside renderpasses are considered transfer operations in terms of barriers.

**Comment by Tony-LunarG** [comment]
You're right - thanks for catching that.

**Comment by Tony-LunarG** [comment]
Fix is checked into master and we've re-released the SDK - 1.0.21.1
